### ISSUE TITLE
Can't gooify anything

### ISSUE THREAD

**Issue by Keltas** [ldtteam/Aequivaleo#13]
I am running 1.16.4 modpack (Direwolf20 1.16 modpack with goo and aequivaleo added) with "aequivaleo-0.1.16-ALPHA" and "Goo-1.16.3-0.8.0.2" however no items are getting assigned values. The minecraft log is filled with "Failed to process recipe:" to the point I struggled to find a paste tool allowing the file to be accepted due to its size. 
The log is in the attached archive: 
[debug-5.log.gz](https://github.com/ldtteam/Aequivaleo/files/5801801/debug-5.log.gz)

The error.log file in aequivaleo folder is empty but there is a single archive with an error file which I've attached. After restarting minecraft I didn't get a new error so it may be unrelated.
[2021-01-02-1.error.gz](https://github.com/ldtteam/Aequivaleo/files/5760699/2021-01-02-1.error.gz)

**Comment by marchermans** [comment]
Should be fixed now.
