### ISSUE TITLE
Deterministic collection instead of hashset for datagen order

### ISSUE THREAD

**Issue by MercuriusXeno** [ldtteam/Aequivaleo#14]
Output produced by datagen can seed non-deterministic key value pairs [names unsorted, won't necessarily be in the same order when run twice] causing git to flag the file for deltas, and other minor reasons why this behavior is less desirable.

Orion already identified that a hashset was being used where a sorted set would nip this.

Issue ported from discord for convenience.

**Comment by Raycoms** [comment]
@Nightenom the solution of this will also be a good solution for us, no?

**Comment by Nightenom** [comment]
Our datagen library is sorted now, not sure what's used here

**Comment by jali-clarke** [comment]
@OrionDevelopment i believe that this has been resolved as of a couple days ago
