### ISSUE TITLE
[Request] Update CF Downloads

### ISSUE THREAD

**Issue by ghost** [ldtteam/Aequivaleo#15]
Can't use Goo without more recent jars.

**Comment by marchermans** [comment]
Why?

**Comment by ghost** [comment]
Goo requires Aequivaleo v 0.1.16-ALPHA-universal.jar (or higher). Aequivaleo's most recent file is aequivaleo-0.0.23.

**Comment by marchermans** [comment]
See the aloha builds on curseforge
As it states in the name of the file you are looking for

**Comment by ghost** [comment]
Hmm, the Alpha only showed in the side column, not in the files list. Weird. Sorry for the misunderstanding. Thanks for the patience. And the work.
