### ISSUE TITLE
Ingredient error logs are empty

### ISSUE THREAD

**Issue by jali-clarke** [ldtteam/Aequivaleo#18]
When creating a new world with the `Create` minecraft mod installed, I see log lines such as:

```
[04Jul2021 20:44:56.106] [ForkJoinPool.commonPool-worker-2/ERROR] [com.ldtteam.aequivaleo.vanilla.VanillaAequivaleoPlugin/]: Failed to process recipe: create:splashing/ice See ingredient error logs for more information.
```

This informs me that I should check the `logs\aequivaleo\ingredient\error.log` file for further information, but that file is empty (exists but zero bytes).

Minecraft `1.16.5`, Forge `36.1.32`, launched via MultiMC 5 (`0.6.12-1530`)

Mod list:
```
aequivaleo-0.1.35-ALPHA-universal.jar # aequivaleo
appleskin-forge-mc1.16.x-2.0.0.jar
create-mc1.16.5_v0.3.1c.jar
FastLeafDecay-v25.jar
Goo-1.16.5-0.8.3.8.jar                # goo
gravestone-1.16.5-1.0.6.jar
inventorysorter-1.16.1-18.1.0.jar
jei-1.16.5-7.7.0.107.jar
JustEnoughResources-1.16.5-0.12.1.121.jar
Patchouli-1.16.4-53.1.jar
StorageDrawers-1.16.3-8.2.2.jar
theoneprobe-1.16-3.1.4.jar
Xaeros_Minimap_21.12.2_Forge_1.16.5.jar
XaerosWorldMap_1.14.4_Forge_1.16.5.jar
```

Please find attached the [debug.log](https://github.com/ldtteam/Aequivaleo/files/6760915/debug.log) and [latest.log](https://github.com/ldtteam/Aequivaleo/files/6760916/latest.log).

**Comment by marchermans** [comment]
This is by design.
The system can't differentiate between ingredients which on purpose don't have an itemstack candidate (aka they need some context like the crafting player) or items who have this on by accident due to a bug.
In general if the log line is written but no error.log entry exists that means that the ingredient does this on purpose and it can be ignored since it is just noice.

**Comment by jali-clarke** [comment]
@OrionDevelopment if that's the case, then there should be no log message telling me to check the ingredient error logs at all.  If there is no further information to be found, I shouldn't be told to look for it.
