### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by darkphan** [ldtteam/Aequivaleo#6]
MC Version: 1.16.3
Forge Version: 32.1.17
aequivaleo version: 0.0.101-ALPHA

Crash report: https://gist.github.com/darkphan/1360a36032131d9bab237bc93e5e4b06

**Comment by Entoarox** [comment]
Can confirm, another user reported this exact same server-only error there.

**Comment by marchermans** [comment]
That looks like a 1.16.3 only error

**Comment by marchermans** [comment]
Fixed in: 
- 1.16.1: https://www.curseforge.com/minecraft/mc-mods/aequivaleo/files/3077525
- 1.16.3: https://www.curseforge.com/minecraft/mc-mods/aequivaleo/files/3077533
